### PR TITLE
added dietmar fiddles parameters

### PR DESCRIPTION
**Pull request by Zaefferer**

### CODE REVIEW

**Comment by Zaefferer** [comment]
Looks like I'm makting progress.

**Comment by MalikaIhle** [comment]
Hi Dietmar yes your pull request looks perfect ! I reopened to merge it so you see how that looks on your side ;)

**Comment by Zaefferer** [comment]
Thank you for merging!

**Comment by Zaefferer** [comment]
Thank you for merging!

**Pull request merged**
