### PR TITLE
Copy Document

### PR DESCRIPTION
**Pull request by SamRiess**
please merge that new species i created

### CODE REVIEW

**Comment by MalikaIhle** [comment]
looks good!

**Comment by MalikaIhle** [comment]
may I ask in which context you followed this tutorial? recommended by someone, as part of a workshop, etc
If you like it feel free to give it a github star here: https://github.com/MalikaIhle/Collaborative-RStudio-GitHub
cheers
Malika

**Comment by SamRiess** [comment]
Yes, you may ask of course.

I'm studying psychology at the LMU Munich and i visited a programming course, organised by other students.
One part of it was a session about version control and they used your workschop to give us a short introduction
In version control and how to apply it in R. Since we're on holidays now, i decided to finish it.

Von: Malika Ihle ***@***.***>
Gesendet: Mittwoch, 21. Februar 2024 16:03
An: MalikaIhle/Collaborative-RStudio-GitHub ***@***.***>
Cc: SamRiess ***@***.***>; Author ***@***.***>
Betreff: Re: [MalikaIhle/Collaborative-RStudio-GitHub] Copy Document (PR #245)


may I ask in which context you followed this tutorial? recommended by someone, as part of a workshop, etc
If you like it feel free to give it a github star here: https://github.com/MalikaIhle/Collaborative-RStudio-GitHub
cheers
Malika

-

**Comment by MalikaIhle** [comment]
oh great! well done to Alp, Martin and Caspar for motivating you and you for finishing on your own!

**Pull request merged**
